name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set environment variables
      run: echo "REACT_APP_API_BASE_URL=$API_BASE_URL" >> $GITHUB_ENV


    - name: Run tests
      run: npm test

 

